id: I2478C812
legacy_id: P009261
ocr_import_info:
  bdrc_scan_id: W13779
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T01:30:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T13:34:05.105244+00:00'
last_modified: 2022-08-29 21:38:04.766606
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W13779
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW13779
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རིག་འཛིན་སྲོག་སྒྲུབ།
  author: ལྷ་བཙུན་ནམ་མཁའ་འཇིགས་མེད།
statistics:
  ocr_word_mean_confidence_index: 0.9145557408736136
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I0784:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0784
      total_pages: 721
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I0784.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9262597618673145
    legacy_id: v003
  I0782:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0782
      total_pages: 946
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0782.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8938833819918794
    legacy_id: v001
  I0783:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0783
      total_pages: 663
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I0783.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9191098397810646
    legacy_id: v002
  I0785:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0785
      total_pages: 463
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I0785.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.909221165097166
    legacy_id: v004
  I0786:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0786
      total_pages: 196
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I0786.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9292503725584743
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
