id: I2478C812
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T01:31:45+00:00'
last_modified: '2022-06-08T09:45:51.806297+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W13779
  title: རིག་འཛིན་སྲོག་སྒྲུབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4D14:
      image_group_id: I0782
      title: ''
      total_pages: 946
      order: 1
      base_file: 4D14.txt
    57C7:
      image_group_id: I0783
      title: ''
      total_pages: 663
      order: 2
      base_file: 57C7.txt
    '8335':
      image_group_id: I0784
      title: ''
      total_pages: 721
      order: 3
      base_file: 8335.txt
    BE55:
      image_group_id: I0785
      title: ''
      total_pages: 463
      order: 4
      base_file: BE55.txt
    D696:
      image_group_id: I0786
      title: ''
      total_pages: 196
      order: 5
      base_file: D696.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
